name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug!

  - type: input
    id: environment
    attributes:
      label: Environment
      description: What OS, version, etc.?
      placeholder: "e.g., Windows 11, v1.0.2"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue in more detail.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide a clear list of steps
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste any logs or add screenshots here

