name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug!

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Version(s) of the application that are affected
      placeholder: "e.g. v1.0.2"

  - type: checkboxes
    id: platforms
    attributes:
      label: Affected Platforms
      description: Select all platforms where the issue occurs
      options:
        - label: Windows [x64]
        - label: Linux [x64]
        - label: Linux [aarch64]
        - label: macOS [x64]

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue in more detail.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide a clear list of steps, if applicable
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste any logs or add screenshots here

