/*
 * This source file was generated by the Gradle 'init' task
 */
package com.urbanelf.iat;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        //Core classUnderTest = new Core();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
